version: "2.1"

services:
  nano:
    build:
      context: .
    network_mode: host
    privileged: true
    cap_add: 
      - SYS_RAWIO
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /root/.Xauthority:/root/.Xauthority
      - ${PWD}/nano:/home/nano
